export const VEHICLE_ENTRY_REQUEST = 'VEHICLE_ENTRY_REQUEST'
export const VEHICLE_ENTRY_SUCCESS = 'VEHICLE_ENTRY_SUCCESS'
export const VEHICLE_ENTRY_FAIL = 'VEHICLE_ENTRY_FAIL'

export const VEHICLE_DETAIL_REQUEST = 'VEHICLE_DETAIL_REQUEST'
export const VEHICLE_DETAIL_SUCCESS = 'VEHICLE_DETAIL_SUCCESS'
export const VEHICLE_DETAIL_FAIL = 'VEHICLE_DETAIL_FAIL'

export const VEHICLE_REQUEST = 'VEHICLE_REQUEST'
export const VEHICLE_SUCCESS = 'VEHICLE_SUCCESS'
export const VEHICLE_FAIL = 'VEHICLE_FAIL'

export const VEHICLE_UPDATE_REQUEST = 'VEHICLE_UPDATE_REQUEST'
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS'
export const VEHICLE_UPDATE_FAIL = 'VEHICLE_UPDATE_FAIL'
export const VEHICLE_UPDATE_RESET = 'VEHICLE_UPDATE_RESET'

export const VEHICLE_DELETE_REQUEST = 'VEHICLE_DELETE_REQUEST'
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS'
export const VEHICLE_DELETE_FAIL = 'VEHICLE_DELETE_FAIL'
export const VEHICLE_DELETE_RESET = 'VEHICLE_DELETE_RESET'

export const COMPANY_ENTRY_REQUEST = 'COMPANY_ENTRY_REQUEST'
export const COMPANY_ENTRY_SUCCESS = 'COMPANY_ENTRY_SUCCESS'
export const COMPANY_ENTRY_FAIL = 'COMPANY_ENTRY_FAIL'

export const COMPANY_DETAIL_REQUEST = 'COMPANY_DETAIL_REQUEST'
export const COMPANY_DETAIL_SUCCESS = 'COMPANY_DETAIL_SUCCESS'
export const COMPANY_DETAIL_FAIL = 'COMPANY_DETAIL_FAIL'

export const COMPANY_REQUEST = 'COMPANY_REQUEST'
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS'
export const COMPANY_FAIL = 'COMPANY_FAIL'

export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST'
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS'
export const COMPANY_UPDATE_FAIL = 'COMPANY_UPDATE_FAIL'
export const COMPANY_UPDATE_RESET = 'COMPANY_UPDATE_RESET'

export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST'
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS'
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL'
export const COMPANY_DELETE_RESET = 'COMPANY_DELETE_RESET'

