export const BILL_CREATE_REQUEST = 'BILL_CREATE_REQUEST';
export const BILL_CREATE_SUCCESS = 'BILL_CREATE_SUCCESS';
export const BILL_CREATE_FAIL = 'BILL_CREATE_FAIL';
export const BILL_CREATE_RESET = 'BILL_CREATE_RESET';

export const ALL_BILL_REQUEST = 'ALL_BILL_REQUEST';
export const ALL_BILL_SUCCESS = 'ALL_BILL_SUCCESS';
export const ALL_BILL_FAIL = 'ALL_BILL_FAIL';

export const BILL_DETAILS_REQUEST = 'BILL_DETAILS_REQUEST';
export const BILL_DETAILS_SUCCESS = 'BILL_DETAILS_SUCCESS';
export const BILL_DETAILS_FAIL = 'BILL_DETAILS_FAIL ';
