export const BILL_CREATE_REQUEST = 'BILL_CREATE_REQUEST';
export const BILL_CREATE_SUCCESS = 'BILL_CREATE_SUCCESS';
export const BILL_CREATE_FAIL = 'BILL_CREATE_FAIL';
export const BILL_CREATE_RESET = 'BILL_CREATE_RESET';