export const DATA_ENTRY_REQUEST = 'DATA_ENTRY_REQUEST'
export const DATA_ENTRY_SUCCESS = 'DATA_ENTRY_SUCCESS'
export const DATA_ENTRY_FAIL = 'DATA_ENTRY_FAIL'

export const DATA_DETAILS_REQUEST = 'DATA_DETAILS_REQUEST'
export const DATA_DETAILS_SUCCESS = 'DATA_DETAILS_SUCCESS'
export const DATA_DETAILS_FAIL = 'DATA_DETAILS_FAIL'

export const DATA_DETAIL_REQUEST = 'DATA_DETAIL_REQUEST'
export const DATA_DETAIL_SUCCESS = 'DATA_DETAIL_SUCCESS'
export const DATA_DETAIL_FAIL = 'DATA_DETAIL_FAIL'

export const DATA_DELETE_REQUEST = 'DATA_DELETE_REQUEST'
export const DATA_DELETE_SUCCESS = 'DATA_DELETE_SUCCESS'
export const DATA_DELETE_FAIL = 'DATA_DELETE_FAIL'
export const DATA_DELETE_RESET = 'DATA_DELETE_RESET'

export const DATA_EDIT_REQUEST = 'DATA_EDIT_REQUEST'
export const DATA_EDIT_SUCCESS = 'DATA_EDIT_SUCCESS'
export const DATA_EDIT_FAIL = 'DATA_EDIT_FAIL'
export const DATA_EDIT_RESET = 'DATA_EDIT_RESET'